### PR TITLE
[Paddle] Support stokes_aligned_zcs_pideeponet

### PR DESCRIPTION
**Pull request by HydrogenSulfate**
Support stokes_aligned_zcs_pideeponet with paddle framework

### CODE REVIEW

**Comment by lululxvi** [comment]
https://github.com/lululxvi/deepxde/pull/1794
Please talk to @lijialin03

**Comment by HydrogenSulfate** [comment]
> #1794 Please talk to @lijialin03

Merge this PR is fine.

**Comment by lijialin03** [comment]
> > #1794 Please talk to @lijialin03
> 
> Merge this PR is fine.

I have closed https://github.com/lululxvi/deepxde/pull/1794.

**Comment by HydrogenSulfate** [comment]
@lululxvi Can you please help to merge this PR.

**Pull request merged**
