### PR TITLE
Add the antiderivative example for multioutput DeepONet 

### PR DESCRIPTION
**Pull request by vl-dud**
The separate PR for [https://github.com/lululxvi/deepxde/pull/1533](https://github.com/lululxvi/deepxde/pull/1533)

### CODE REVIEW

**Comment by lululxvi** [comment]
Double check this PR.

**Comment by vl-dud** [comment]
I checked it. The example works correctly for all strategies, both with TF 1.x and 2.x.

**Comment by lululxvi** [comment]
Then this example may be redundant and would make the reader confused. We already have this https://github.com/lululxvi/deepxde/pull/1549/files , so it is not necessary to have this example.

**Comment by vl-dud** [comment]
Ok, I'm closing this request.

**Pull request closed without merging**
