### PR TITLE
 Allow specifying amount of boundary condition test points 

### PR DESCRIPTION
**Pull request by g-w1**
Something similar can be done in `data/pde_operator.py` and I may do this in a future pull request.

Should I add `num_test_boundary` to the examples? I'm not sure if this is a problem in the real-world. It seems to me that doing this would prevent (or at least detect) overfitting to the boundary conditions selected.

I also fixed a trivial TODO in `pde.py` (rename `train_x_all` to `train_x_pde`). Let me know if you want me to split this into a seperate PR.

### CODE REVIEW

**Comment by lululxvi** [comment]
> I also fixed a trivial TODO in `pde.py` (rename `train_x_all` to `train_x_pde`). Let me know if you want me to split this into a seperate PR.

Yes, too many changes in this PR. Please split.

**Comment by g-w1** [comment]
> Yes, too many changes in this PR. Please split.

I have split it into #1113 .

**Comment by lululxvi** [comment]
There might be some classes that also use `num_test`. You may double check.

**Comment by lululxvi** [comment]
Another main issue is that in `losses`, we use `self.num_bcs` for both training and testing. If you generate test boundary points separately, then `self.num_bcs` doesn't work for test points.

**Comment by g-w1** [comment]
I will modify `ide.py` and `fpde.py` to add `num_test_domain` and `num_test_boundary` and will creat `self.num_bcs_train` and `self.num_bcs_test`. Thank you for the feedback.

**Pull request closed without merging**
