### PR TITLE
Backend paddle: add&modify nets; add regularizer; add optimizers;

### PR DESCRIPTION
**Pull request by lijialin03**
For paddle backend:
1. add mfnn net
2. add regularization for fnn net
3. add l1/l2 regularizer
4. add sgd/rmsprop/adamw
5. support examples in examples/function/

For others:
1. refactor regularizer to be compatible with multiple backends

Comparison of results(tf vs paddle)：
dataset.py
imageimage

func_uncertainty.py
image截屏2024-11-27 16 08 40

func.py
imageimage

mf_dataset.py
imageimage

mf_func.py
imageimage

### CODE REVIEW

**Comment by lululxvi** [comment]
There are many modifications. I suggest to make a few PRs so that it is easy to review and merge.

**Comment by lijialin03** [comment]
> There are many modifications. I suggest to make a few PRs so that it is easy to review and merge.

Ok, I split this PR into：
https://github.com/lululxvi/deepxde/pull/1893
https://github.com/lululxvi/deepxde/pull/1894
https://github.com/lululxvi/deepxde/pull/1895

**Comment by lululxvi** [comment]
Should we close this?

**Comment by lijialin03** [comment]
> Should we close this?

Yes, it should be closed. Or it can be used as a list, which means it could be closed until the split PRs are merged.

**Pull request closed without merging**
