### PR TITLE
1D Reaction Diffusion Example

### PR DESCRIPTION
**Pull request by danielt25**
Added example of training 1D PDE data to deepxde.  This includes the .py file, the ipython notebook, the mathematica file that approximated the training data, and an excel sheet for the training data.

### CODE REVIEW

**Comment by lululxvi** [comment]
If the .py file and ipython notebook contain the same content, then only .py file should be included.

**Comment by kookma** [comment]
@danielt25 - please revise the PR and resubmit as @lululxvi advised!
reaction-diffusion is essential in ChemE.

**Comment by lululxvi** [comment]
@kookma I guess @danielt25 won't work on this PR. You can submit a new PR baed on his code, if you would like to.

**Comment by kookma** [comment]
Hi @lululxvi 
Sure, I go through it! By the way by end of semester two of my students have taken mini projects on using deepxde in chemical reaction engineering course. I would be happy if you have any special cases in mind which we can work on them and then submit PRs to be added into deepxde/examples.

**Comment by lululxvi** [comment]
I don't have any special cases in mind. You are welcome to submit any cases you like.

**Pull request closed without merging**
