### PR TITLE
speed up construction of indices for sparse tensor

### PR DESCRIPTION
**Pull request by HydrogenSulfate**
replace list(zip()) with nested list comprehension to speed up construction of indices for sparse tensor

python3.7 

```python
import time
import random

n = 1252319
array = [[random.randint(0, n), random.randint(0, n)] for _ in range(n)]

s = time.perf_counter()
res1 = zip(*array)
e1 = time.perf_counter()
print(f"zip(...) cost: {e1 - s}")

s = time.perf_counter()
res1 = list(res1)
e2 = time.perf_counter()
print(f"list(...) cost: {e2 - s}")

s = time.perf_counter()
res2 = [tuple([p[0] for p in array]), tuple([p[1] for p in array])]
e2 = time.perf_counter()
print(f"list comprehension cost: {e2 - s}")

print(res1 == res2)

"""
zip(...) cost: 0.6884705810807645
list(...) cost: 0.0964503069408238
list comprehension cost: 0.1501797849778086
True
"""
```

### CODE REVIEW

**Comment by lululxvi** [comment]
How about new versions, such as Python 3.11?

**Comment by HydrogenSulfate** [comment]
> How about new versions, such as Python 3.11?

zip still slower than list comprehension
```
zip(...) cost: 0.6185596429277211
list(...) cost: 0.08116732793860137
list comprehension cost: 0.12146345409564674
True
```

**Comment by lululxvi** [comment]
Personally, I like `list(zip(*indices))` as it is more elegant, but of course, speed is very important. The difference is about 0.6s. How does this affect the total cost of training?

**Comment by HydrogenSulfate** [comment]
> Personally, I like `list(zip(*indices))` as it is more elegant, but of course, speed is very important. The difference is about 0.6s. How does this affect the total cost of training?

52876s vs 2888s，with display_every=1

**Pull request merged**
