### PR TITLE
mini-implementation of resample

### PR DESCRIPTION
**Pull request by smao-astro**
See discussion at #175.

### CODE REVIEW

**Comment by smao-astro** [comment]
Notice that this modification could break class that depend on `deepxde.data.pde.PDE` such as `deepxde.data.ide.IDE` and `deepxde.data.fpde.FPDE` and other user defined class if them depends on `pde.train_x_all`, unfortunately we currently do not have time to fix.

**Comment by lululxvi** [comment]
Because it breaks other parts of DeepXDE, could you add a new class instead of modifying `PDE`?

**Comment by lululxvi** [comment]
Should we close this?

**Comment by smao-astro** [comment]
Yes, closed.

**Pull request closed without merging**
