### PR TITLE
Add `CITATION.cff`

### LINKED ISSUE #423: Add a "Cite this repository" dropdown option in the repository
GitHub now provides a feature to add a "Cite this repository" option using a `CITATION.cff` file. It looks something like this (in the about section) -
image

I'd like to take this up if everyone want it to be added in.

### PR DESCRIPTION
**Pull request by Saransh-cpp**
Closes #423 

## Additions
- Added the `CITATIONS.cff` file which will render a `"Cite this repository"` dropdown menu in the `About` section of the repository.

An orcid URL can also be added for each author but I couldn't find any in the repository, I'll be happy to add them if someone can comment them down.

Apologies if I misspelled any name.

The working dropdown can be viewed [here](https://github.com/Saransh-cpp/deepxde/tree/add-citation.cff).

### CODE REVIEW

**Comment by lululxvi** [comment]
Is cff-version 1.2.0 or 1.1.0?

I found a website that generates the file: https://bit.ly/cffinit 

ORCID: Lu Lu: https://orcid.org/0000-0002-5476-5768
 George Karniadakis : https://orcid.org/0000-0002-9713-7120

**Comment by Saransh-cpp** [comment]
Yes, the version should be updated. I referred to the [examples](https://github.com/citation-file-format/citation-file-format/tree/main/examples) available in their GitHub repository but the website seems to do the trick. I'll make the necessary changes.

**Comment by lululxvi** [comment]
I find a few things:
1. The `journal` part seems not been used in the generated citation.
2. There is no need to be  Version specific .

Here is what I get from the website https://bit.ly/cffinit, which you can directly use:

# This CITATION.cff file was generated with cffinit.
# Visit https://bit.ly/cffinit to generate yours today!

cff-version: 1.2.0
title: >-
  DeepXDE: A deep learning library for solving
  differential equations
message: >-
  If you use this software, please cite it using the
  metadata from this file.
type: software
authors:
  - given-names: Lu
    orcid: 'https://orcid.org/0000-0002-5476-5768'
    family-names: Lu
    affiliation: Massachusetts Institute of Technology
  - given-names: Xuhui
    family-names: Meng
    affiliation: Brown University
  - family-names: Mao
    given-names: Zhiping
    affiliation: Xiamen University
  - family-names: Karniadakis
    given-names: George Em
    orcid: 'https://orcid.org/0000-0002-9713-7120'
    affiliation: Brown University
identifiers:
  - type: doi
    value: 10.1137/19M1274067
repository-code: 'https://github.com/lululxvi/deepxde'
url: 'https://deepxde.readthedocs.io'
license: Apache-2.0

**Comment by Saransh-cpp** [comment]
Thank you @lululxvi!

**Pull request merged**
