### PR TITLE
Add the method resample_train_points to PDEOperator

### PR DESCRIPTION
**Pull request by vl-dud**
PR is required to use PDEPointResampler callback with PDEOperator.

### CODE REVIEW

**Comment by lululxvi** [comment]
Have you tested the code?

**Comment by vl-dud** [comment]
> Have you tested the code?

Yes, I have

**Comment by lululxvi** [comment]
Why the check failed?

**Comment by vl-dud** [comment]
> Why the check failed?

Due to an issue that was fixed [later](https://github.com/lululxvi/deepxde/pull/1760)

**Pull request merged**
